using FluxImproverChunk = FluxImprover.Models.IEnrichedChunk;
using FluxIndexChunk = FluxIndex.Core.Application.Interfaces.IEnrichedChunk;

namespace FluxIndex.SDK.Extensions.FluxImprover.Adapters;

/// <summary>
/// Adapter that bridges FluxIndex.Core.IEnrichedChunk to FluxImprover.Abstractions.IEnrichedChunk.
/// This allows FluxImprover services to process chunks from FluxIndex.
/// </summary>
/// <remarks>
/// Property mapping:
/// - FluxIndex.ChunkId → FluxImprover.Id
/// - FluxIndex.Content → FluxImprover.Text
/// - FluxIndex.Source.DocumentId → FluxImprover.SourceId
/// - FluxIndex.HeadingPath (List) → FluxImprover.HeadingPath (joined string)
/// - FluxImprover.Summary → null (generated by enrichment)
/// - FluxImprover.Keywords → null (generated by enrichment)
/// - FluxIndex-specific properties → FluxImprover.Metadata dictionary
/// </remarks>
public sealed class EnrichedChunkAdapter : FluxImproverChunk
{
    private readonly FluxIndexChunk _fluxIndexChunk;
    private IReadOnlyDictionary<string, object>? _cachedMetadata;

    /// <summary>
    /// Creates a new adapter wrapping the FluxIndex enriched chunk.
    /// </summary>
    /// <param name="fluxIndexChunk">The FluxIndex enriched chunk to wrap.</param>
    /// <exception cref="ArgumentNullException">Thrown when fluxIndexChunk is null.</exception>
    public EnrichedChunkAdapter(FluxIndexChunk fluxIndexChunk)
    {
        _fluxIndexChunk = fluxIndexChunk ?? throw new ArgumentNullException(nameof(fluxIndexChunk));
    }

    /// <inheritdoc />
    public string Id => _fluxIndexChunk.ChunkId;

    /// <inheritdoc />
    public string Text => _fluxIndexChunk.Content;

    /// <inheritdoc />
    public string SourceId => _fluxIndexChunk.Source.SourceId;

    /// <inheritdoc />
    public string? HeadingPath
    {
        get
        {
            var path = _fluxIndexChunk.HeadingPath;
            if (path == null || path.Count == 0)
                return null;
            return string.Join(" > ", path);
        }
    }

    /// <inheritdoc />
    /// <remarks>
    /// Summary is not available in FluxIndex chunks.
    /// This property is populated by FluxImprover's enrichment services.
    /// </remarks>
    public string? Summary => null;

    /// <inheritdoc />
    /// <remarks>
    /// Keywords are not available in FluxIndex chunks.
    /// This property is populated by FluxImprover's enrichment services.
    /// </remarks>
    public IReadOnlyList<string>? Keywords => null;

    /// <inheritdoc />
    /// <remarks>
    /// Contains FluxIndex-specific properties that don't have direct mappings:
    /// - ChunkIndex: Document position
    /// - Quality: Chunk quality score (0.0-1.0)
    /// - ContextDependency: Context dependency score (0.0-1.0)
    /// - TokenCount: Estimated token count
    /// - StartPage/EndPage: Page range
    /// - SectionTitle: Current section title
    /// - FileName/ContentType: Source file information
    /// </remarks>
    public IReadOnlyDictionary<string, object>? Metadata
    {
        get
        {
            if (_cachedMetadata != null)
                return _cachedMetadata;

            var metadata = new Dictionary<string, object>
            {
                ["ChunkIndex"] = _fluxIndexChunk.ChunkIndex,
                ["Quality"] = _fluxIndexChunk.Quality,
                ["ContextDependency"] = _fluxIndexChunk.ContextDependency
            };

            // Add optional properties only if they have values
            if (_fluxIndexChunk.TokenCount.HasValue)
                metadata["TokenCount"] = _fluxIndexChunk.TokenCount.Value;

            if (_fluxIndexChunk.StartPage.HasValue)
                metadata["StartPage"] = _fluxIndexChunk.StartPage.Value;

            if (_fluxIndexChunk.EndPage.HasValue)
                metadata["EndPage"] = _fluxIndexChunk.EndPage.Value;

            if (!string.IsNullOrEmpty(_fluxIndexChunk.SectionTitle))
                metadata["SectionTitle"] = _fluxIndexChunk.SectionTitle;

            // Add source metadata
            var source = _fluxIndexChunk.Source;
            if (!string.IsNullOrEmpty(source.FilePath))
                metadata["FilePath"] = source.FilePath;

            if (!string.IsNullOrEmpty(source.SourceType))
                metadata["SourceType"] = source.SourceType;

            if (!string.IsNullOrEmpty(source.Title))
                metadata["Title"] = source.Title;

            if (!string.IsNullOrEmpty(source.Author))
                metadata["Author"] = source.Author;

            if (!string.IsNullOrEmpty(source.Language))
                metadata["Language"] = source.Language;

            if (source.WordCount > 0)
                metadata["WordCount"] = source.WordCount;

            _cachedMetadata = metadata;
            return _cachedMetadata;
        }
    }

    /// <summary>
    /// Gets the underlying FluxIndex chunk for advanced scenarios.
    /// </summary>
    public FluxIndexChunk UnderlyingChunk => _fluxIndexChunk;
}
