using FluxIndex.Core.Application.Interfaces;
using FluxIndex.Core.Application.Services.KeywordSearch;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Npgsql;
using System.Data.Common;

namespace FluxIndex.Storage.PostgreSQL.KeywordSearch;

/// <summary>
/// PostgreSQL-backed implementation of <see cref="IKeywordSearchService"/>.
/// Persists the inverted index in the same database as the vector store, so the keyword leg of a
/// hybrid search survives a restart and is shared by every process pointed at that database.
/// <para>
/// The index behavior — schema shape, tokenization, BM25 ranking, maintenance — lives in
/// <see cref="RelationalKeywordSearchService"/> so it cannot diverge from the other SQL backends.
/// What remains here is PostgreSQL dialect: identity columns, its upsert syntax, and an array
/// parameter in place of an inlined id list.
/// </para>
/// </summary>
public sealed class PostgresKeywordSearchService : RelationalKeywordSearchService
{
    private readonly string _connectionString;

    /// <summary>Creates the service from the configured PostgreSQL options.</summary>
    public PostgresKeywordSearchService(
        IOptions<PostgreSQLOptions> options,
        ILogger<PostgresKeywordSearchService> logger,
        ITextAnalyzer? analyzer = null,
        KeywordFieldOptions? fields = null)
        : base(logger, analyzer, fields)
    {
        ArgumentNullException.ThrowIfNull(options);
        // PostgreSQLOptions.CommandTimeout reaches the keyword index too, not only the vector store: a full keyword
        // rebuild on a large index needs the operator to be able to raise it.
        _connectionString = new NpgsqlConnectionStringBuilder(options.Value.ConnectionString)
        {
            CommandTimeout = options.Value.CommandTimeout,
        }.ConnectionString;
    }

    /// <summary>
    /// Creates the service against an explicit connection string. Its <c>Command Timeout</c> (Npgsql default 30 s)
    /// applies to every statement, including document-frequency maintenance during a rebuild.
    /// </summary>
    public PostgresKeywordSearchService(
        string connectionString,
        ILogger<PostgresKeywordSearchService> logger,
        ITextAnalyzer? analyzer = null,
        KeywordFieldOptions? fields = null)
        : base(logger, analyzer, fields)
    {
        _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
    }

    /// <inheritdoc />
    protected override string BackendName => "PostgreSQL";

    /// <summary>
    /// Term ids per document-frequency statement. Each statement costs about the number of terms it names, and a
    /// rebuild of one large entry touches tens of thousands — sent as one statement it ran past the command timeout
    /// (measured: ~68 µs per term on a 1.5 M-posting index). Batches stay inside the caller's transaction, so the
    /// result is the same.
    /// </summary>
    protected override int TermIdBatchSize => 2_000;

    /// <summary>
    /// A plain connection is enough here: the keyword index stores no vector-typed columns, so it
    /// needs neither the pgvector plugin nor the dynamic-JSON data source the vector store builds.
    /// </summary>
    protected override DbConnection CreateConnection() => new NpgsqlConnection(_connectionString);

    /// <summary>
    /// Mirrors the SQLite schema one-for-one — same relations, same columns, same indexes — because
    /// the shared BM25 implementation queries them by name. Only the types and the identity syntax
    /// are PostgreSQL's.
    /// <para>
    /// Terms are stored already lower-cased by the tokenizer and looked up the same way, so a plain
    /// unique constraint is all the index needs; no case-insensitive collation is involved.
    /// </para>
    /// </summary>
    protected override string SchemaDdl => """
        CREATE TABLE IF NOT EXISTS bm25_terms (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            term text NOT NULL UNIQUE,
            document_frequency integer NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS bm25_postings (
            term_id bigint NOT NULL REFERENCES bm25_terms(id) ON DELETE CASCADE,
            chunk_id text NOT NULL,
            term_frequency integer NOT NULL,
            document_length integer NOT NULL,
            PRIMARY KEY (term_id, chunk_id)
        );

        CREATE TABLE IF NOT EXISTS bm25_field_postings (
            term_id bigint NOT NULL REFERENCES bm25_terms(id) ON DELETE CASCADE,
            chunk_id text NOT NULL,
            field text NOT NULL,
            term_frequency integer NOT NULL,
            field_length integer NOT NULL,
            document_length integer NOT NULL,
            PRIMARY KEY (term_id, chunk_id, field)
        );

        CREATE TABLE IF NOT EXISTS bm25_chunks (
            chunk_id text PRIMARY KEY,
            document_id text NOT NULL,
            chunk_index integer NOT NULL DEFAULT 0,
            content text NOT NULL,
            token_count integer NOT NULL DEFAULT 0,
            metadata text
        );

        CREATE TABLE IF NOT EXISTS bm25_chunk_metadata (
            chunk_id text NOT NULL,
            meta_key text NOT NULL,
            meta_value text NOT NULL,
            PRIMARY KEY (chunk_id, meta_key, meta_value)
        );

        CREATE INDEX IF NOT EXISTS idx_bm25_chunk_metadata_lookup
            ON bm25_chunk_metadata (meta_key, meta_value);

        CREATE TABLE IF NOT EXISTS bm25_statistics (
            key text PRIMARY KEY,
            value double precision NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_bm25_terms_term ON bm25_terms(term);
        CREATE INDEX IF NOT EXISTS idx_bm25_postings_chunk ON bm25_postings(chunk_id);
        CREATE INDEX IF NOT EXISTS idx_bm25_field_postings_chunk ON bm25_field_postings(chunk_id);
        CREATE INDEX IF NOT EXISTS idx_bm25_chunks_document ON bm25_chunks(document_id);
        """;

    /// <inheritdoc />
    protected override string UpsertChunkSql => """
        INSERT INTO bm25_chunks (chunk_id, document_id, chunk_index, content, token_count, metadata)
        VALUES (@chunkId, @documentId, @chunkIndex, @content, @tokenCount, @metadata)
        ON CONFLICT (chunk_id) DO UPDATE SET
            document_id = excluded.document_id,
            chunk_index = excluded.chunk_index,
            content = excluded.content,
            token_count = excluded.token_count,
            metadata = excluded.metadata;
        """;

    /// <summary>
    /// <c>DO NOTHING</c> leaves an existing row unlocked. The no-op <c>DO UPDATE</c> this replaced returned the id in
    /// one statement but locked the row to the end of the transaction, so every writer sharing the word waited for
    /// the whole batch.
    /// </summary>
    protected override string InsertTermIfAbsentSql => """
        INSERT INTO bm25_terms (term, document_frequency) VALUES (@term, 0)
        ON CONFLICT (term) DO NOTHING;
        """;

    /// <summary>
    /// One statement for the whole set, in the given order (the rows are inserted in the order the sorted select
    /// produces them), so a registration costs one round trip rather than one per term.
    /// </summary>
    protected override async Task InsertTermsAsync(DbConnection connection, IReadOnlyList<string> orderedTerms, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO bm25_terms (term, document_frequency)
            SELECT t, 0 FROM unnest(@terms) AS t ORDER BY t COLLATE "C"
            ON CONFLICT (term) DO NOTHING;
            """;
        AddParameter(command, "@terms", orderedTerms.ToArray());
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    /// <summary>Writers run concurrently here, so new terms are committed before the write transaction starts.</summary>
    protected override bool RegistersTermsInOwnTransaction => true;

    /// <summary>
    /// <c>NO KEY UPDATE</c>, not <c>UPDATE</c>: every posting insert takes a key-share lock on its term row through
    /// the foreign key and holds it to commit, and <c>FOR UPDATE</c> would wait for every such writer's whole batch.
    /// </summary>
    protected override string? TermRowLockClause => "FOR NO KEY UPDATE";

    /// <summary>
    /// A zero-frequency row another writer holds is one that writer is giving a posting; it is skipped rather than
    /// waited for (and would be kept anyway).
    /// </summary>
    protected override string? TermCleanupLockClause => "FOR UPDATE SKIP LOCKED";

    /// <summary>
    /// One transaction-scoped advisory lock per chunk id, in ascending key order so two writers cannot wait on each
    /// other in both directions. Keys are a hash of the chunk id under a fixed class id; a collision only makes two
    /// unrelated chunks take turns.
    /// </summary>
    protected override async Task LockChunksAsync(DbConnection connection, IReadOnlyCollection<string> chunkIds, CancellationToken cancellationToken)
    {
        foreach (var key in chunkIds.Select(ChunkLockKey).Distinct().Order())
        {
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT pg_advisory_xact_lock(@lockClass, @lockKey)";
            AddParameter(command, "@lockClass", ChunkLockClass);
            AddParameter(command, "@lockKey", key);
            await command.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
        }
    }

    /// <summary>The advisory-lock class id of keyword-index chunk locks (ASCII "FXKC").</summary>
    private const int ChunkLockClass = 0x46584B43;

    /// <summary>FNV-1a over the UTF-16 code units of the chunk id - stable across processes, unlike string.GetHashCode.</summary>
    private static int ChunkLockKey(string chunkId)
    {
        var hash = 2166136261u;
        foreach (var c in chunkId)
        {
            hash ^= c;
            hash *= 16777619u;
        }

        return unchecked((int)hash);
    }

    /// <summary>A posting whose term row a concurrent cleanup removed fails its foreign key (<c>23503</c>).</summary>
    protected override bool IsTermRowRemovedFailure(DbException exception)
        => exception is PostgresException { SqlState: PostgresErrorCodes.ForeignKeyViolation, TableName: "bm25_postings" or "bm25_field_postings" };

    /// <inheritdoc />
    protected override string BuildTermTextPredicate(DbCommand command, string columnRef, IReadOnlyCollection<string> terms)
    {
        AddParameter(command, "@terms", terms.ToArray());
        return $"{columnRef} = ANY(@terms)";
    }

    /// <inheritdoc />
    protected override string UpsertPostingSql => """
        INSERT INTO bm25_postings (term_id, chunk_id, term_frequency, document_length)
        VALUES (@termId, @chunkId, @tf, @docLen)
        ON CONFLICT (term_id, chunk_id) DO UPDATE SET
            term_frequency = excluded.term_frequency,
            document_length = excluded.document_length;
        """;

    /// <inheritdoc />
    protected override string UpsertFieldPostingSql => """
        INSERT INTO bm25_field_postings (term_id, chunk_id, field, term_frequency, field_length, document_length)
        VALUES (@termId, @chunkId, @field, @tf, @fieldLen, @docLen)
        ON CONFLICT (term_id, chunk_id, field) DO UPDATE SET
            term_frequency = excluded.term_frequency,
            field_length = excluded.field_length,
            document_length = excluded.document_length;
        """;

    /// <inheritdoc />
    protected override string UpsertStatisticSql => """
        INSERT INTO bm25_statistics (key, value) VALUES (@key, @value)
        ON CONFLICT (key) DO UPDATE SET value = excluded.value;
        """;

    /// <summary>
    /// Nothing to run. PostgreSQL reclaims space through autovacuum, and an explicit VACUUM cannot run
    /// inside a transaction and requires table ownership — so issuing one here would fail for exactly
    /// the deployments that share a database with other applications.
    /// </summary>
    protected override string? CompactSql => null;

    /// <inheritdoc />
    /// <remarks>Under <see cref="PostgresSchemaLock"/>: keyword indexes started at the same moment take turns.</remarks>
    protected override Task ExecuteSchemaDdlAsync(DbConnection connection, CancellationToken cancellationToken) =>
        PostgresSchemaLock.RunAsync(connection, () => base.ExecuteSchemaDdlAsync(connection, cancellationToken), cancellationToken);

    /// <summary>
    /// PostgreSQL has a real array type, so the ids travel as one parameter. The statement stays a
    /// fixed size no matter how many terms a batch touched, which is why
    /// <see cref="RelationalKeywordSearchService.TermIdBatchSize"/> is left unbounded here.
    /// </summary>
    protected override string BuildTermIdPredicate(
        DbCommand command,
        string columnRef,
        IReadOnlyCollection<long> termIds)
    {
        AddParameter(command, "@termIds", termIds.ToArray());
        return $"{columnRef} = ANY(@termIds)";
    }
}
