using FluxIndex.Core.Application.Interfaces;
using FluxIndex.Core.Application.Services.KeywordSearch;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Npgsql;
using System.Data.Common;

namespace FluxIndex.Storage.PostgreSQL.KeywordSearch;

/// <summary>
/// PostgreSQL-backed implementation of <see cref="IKeywordSearchService"/>.
/// Persists the inverted index in the same database as the vector store, so the keyword leg of a
/// hybrid search survives a restart and is shared by every process pointed at that database.
/// <para>
/// The index behavior — schema shape, tokenization, BM25 ranking, maintenance — lives in
/// <see cref="RelationalKeywordSearchService"/> so it cannot diverge from the other SQL backends.
/// What remains here is PostgreSQL dialect: identity columns, its upsert syntax, and an array
/// parameter in place of an inlined id list.
/// </para>
/// </summary>
public sealed class PostgresKeywordSearchService : RelationalKeywordSearchService
{
    private readonly string _connectionString;

    /// <summary>Creates the service from the configured PostgreSQL options.</summary>
    public PostgresKeywordSearchService(
        IOptions<PostgreSQLOptions> options,
        ILogger<PostgresKeywordSearchService> logger)
        : base(logger)
    {
        ArgumentNullException.ThrowIfNull(options);
        _connectionString = options.Value.ConnectionString;
    }

    /// <summary>Creates the service against an explicit connection string.</summary>
    public PostgresKeywordSearchService(
        string connectionString,
        ILogger<PostgresKeywordSearchService> logger)
        : base(logger)
    {
        _connectionString = connectionString ?? throw new ArgumentNullException(nameof(connectionString));
    }

    /// <inheritdoc />
    protected override string BackendName => "PostgreSQL";

    /// <summary>
    /// A plain connection is enough here: the keyword index stores no vector-typed columns, so it
    /// needs neither the pgvector plugin nor the dynamic-JSON data source the vector store builds.
    /// </summary>
    protected override DbConnection CreateConnection() => new NpgsqlConnection(_connectionString);

    /// <summary>
    /// Mirrors the SQLite schema one-for-one — same relations, same columns, same indexes — because
    /// the shared BM25 implementation queries them by name. Only the types and the identity syntax
    /// are PostgreSQL's.
    /// <para>
    /// Terms are stored already lower-cased by the tokenizer and looked up the same way, so a plain
    /// unique constraint is all the index needs; no case-insensitive collation is involved.
    /// </para>
    /// </summary>
    protected override string SchemaDdl => """
        CREATE TABLE IF NOT EXISTS bm25_terms (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            term text NOT NULL UNIQUE,
            document_frequency integer NOT NULL DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS bm25_postings (
            term_id bigint NOT NULL REFERENCES bm25_terms(id) ON DELETE CASCADE,
            chunk_id text NOT NULL,
            term_frequency integer NOT NULL,
            document_length integer NOT NULL,
            PRIMARY KEY (term_id, chunk_id)
        );

        CREATE TABLE IF NOT EXISTS bm25_chunks (
            chunk_id text PRIMARY KEY,
            document_id text NOT NULL,
            chunk_index integer NOT NULL DEFAULT 0,
            content text NOT NULL,
            token_count integer NOT NULL DEFAULT 0,
            metadata text
        );

        CREATE TABLE IF NOT EXISTS bm25_chunk_metadata (
            chunk_id text NOT NULL,
            meta_key text NOT NULL,
            meta_value text NOT NULL,
            PRIMARY KEY (chunk_id, meta_key, meta_value)
        );

        CREATE INDEX IF NOT EXISTS idx_bm25_chunk_metadata_lookup
            ON bm25_chunk_metadata (meta_key, meta_value);

        CREATE TABLE IF NOT EXISTS bm25_statistics (
            key text PRIMARY KEY,
            value double precision NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_bm25_terms_term ON bm25_terms(term);
        CREATE INDEX IF NOT EXISTS idx_bm25_postings_chunk ON bm25_postings(chunk_id);
        CREATE INDEX IF NOT EXISTS idx_bm25_chunks_document ON bm25_chunks(document_id);
        """;

    /// <inheritdoc />
    protected override string UpsertChunkSql => """
        INSERT INTO bm25_chunks (chunk_id, document_id, chunk_index, content, token_count, metadata)
        VALUES (@chunkId, @documentId, @chunkIndex, @content, @tokenCount, @metadata)
        ON CONFLICT (chunk_id) DO UPDATE SET
            document_id = excluded.document_id,
            chunk_index = excluded.chunk_index,
            content = excluded.content,
            token_count = excluded.token_count,
            metadata = excluded.metadata;
        """;

    /// <summary>
    /// The no-op update is what makes the statement return an id for an existing term as well —
    /// <c>ON CONFLICT DO NOTHING</c> would return no row at all.
    /// </summary>
    protected override string UpsertTermReturningIdSql => """
        INSERT INTO bm25_terms (term, document_frequency) VALUES (@term, 0)
        ON CONFLICT (term) DO UPDATE SET term = excluded.term
        RETURNING id;
        """;

    /// <inheritdoc />
    protected override string UpsertPostingSql => """
        INSERT INTO bm25_postings (term_id, chunk_id, term_frequency, document_length)
        VALUES (@termId, @chunkId, @tf, @docLen)
        ON CONFLICT (term_id, chunk_id) DO UPDATE SET
            term_frequency = excluded.term_frequency,
            document_length = excluded.document_length;
        """;

    /// <summary>
    /// Both rows go in one statement rather than two: Npgsql matches parameters per statement, and a
    /// two-statement batch where each references only one of them is needlessly fragile.
    /// </summary>
    protected override string UpsertStatisticSql => """
        INSERT INTO bm25_statistics (key, value)
        VALUES ('total_documents', @totalDocs), ('avg_doc_length', @avgLength)
        ON CONFLICT (key) DO UPDATE SET value = excluded.value;
        """;

    /// <summary>
    /// Nothing to run. PostgreSQL reclaims space through autovacuum, and an explicit VACUUM cannot run
    /// inside a transaction and requires table ownership — so issuing one here would fail for exactly
    /// the deployments that share a database with other applications.
    /// </summary>
    protected override string? CompactSql => null;

    /// <summary>
    /// PostgreSQL has a real array type, so the ids travel as one parameter. The statement stays a
    /// fixed size no matter how many terms a batch touched, which is why
    /// <see cref="RelationalKeywordSearchService.TermIdBatchSize"/> is left unbounded here.
    /// </summary>
    protected override string BuildTermIdPredicate(
        DbCommand command,
        string columnRef,
        IReadOnlyCollection<long> termIds)
    {
        AddParameter(command, "@termIds", termIds.ToArray());
        return $"{columnRef} = ANY(@termIds)";
    }
}
