using FluentAssertions;
using FluxIndex.Extensions.FluxImprover.Adapters;
using Moq;
using Xunit;
using FluxIndexChunk = FluxIndex.Core.Application.Interfaces.IEnrichedChunk;
using FluxIndexSource = FluxIndex.Core.Application.Interfaces.ISourceMetadata;
using FluxImproverChunk = FluxImprover.Models.IEnrichedChunk;

namespace FluxIndex.Extensions.FluxImprover.Tests.Adapters;

/// <summary>
/// Tests for EnrichedChunkAdapter - adapts FluxIndex IEnrichedChunk to FluxImprover's interface
/// </summary>
public class EnrichedChunkAdapterTests
{
    private readonly Mock<FluxIndexChunk> _mockFluxIndexChunk;
    private readonly Mock<FluxIndexSource> _mockSourceMetadata;

    public EnrichedChunkAdapterTests()
    {
        _mockSourceMetadata = new Mock<FluxIndexSource>();
        _mockSourceMetadata.Setup(s => s.SourceId).Returns("doc-123");
        _mockSourceMetadata.Setup(s => s.FilePath).Returns("/path/to/test.pdf");
        _mockSourceMetadata.Setup(s => s.SourceType).Returns("pdf");
        _mockSourceMetadata.Setup(s => s.WordCount).Returns(1024);
        _mockSourceMetadata.Setup(s => s.Title).Returns("Test Document");
        _mockSourceMetadata.Setup(s => s.Author).Returns("Test Author");
        _mockSourceMetadata.Setup(s => s.Language).Returns("en");

        _mockFluxIndexChunk = new Mock<FluxIndexChunk>();
        _mockFluxIndexChunk.Setup(c => c.ChunkId).Returns("chunk-001");
        _mockFluxIndexChunk.Setup(c => c.Content).Returns("This is the chunk content.");
        _mockFluxIndexChunk.Setup(c => c.ChunkIndex).Returns(0);
        _mockFluxIndexChunk.Setup(c => c.HeadingPath).Returns(new List<string> { "Chapter 1", "Section 1.1" });
        _mockFluxIndexChunk.Setup(c => c.SectionTitle).Returns("Section 1.1");
        _mockFluxIndexChunk.Setup(c => c.StartPage).Returns(1);
        _mockFluxIndexChunk.Setup(c => c.EndPage).Returns(2);
        _mockFluxIndexChunk.Setup(c => c.Quality).Returns(0.85);
        _mockFluxIndexChunk.Setup(c => c.ContextDependency).Returns(0.3);
        _mockFluxIndexChunk.Setup(c => c.TokenCount).Returns(50);
        _mockFluxIndexChunk.Setup(c => c.Source).Returns(_mockSourceMetadata.Object);
    }

    [Fact]
    public void Id_ReturnsChunkId()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.Id.Should().Be("chunk-001");
    }

    [Fact]
    public void Text_ReturnsContent()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.Text.Should().Be("This is the chunk content.");
    }

    [Fact]
    public void SourceId_ReturnsDocumentId()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.SourceId.Should().Be("doc-123");
    }

    [Fact]
    public void HeadingPath_ReturnsJoinedPath()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.HeadingPath.Should().Be("Chapter 1 > Section 1.1");
    }

    [Fact]
    public void HeadingPath_WithEmptyPath_ReturnsNull()
    {
        // Arrange
        _mockFluxIndexChunk.Setup(c => c.HeadingPath).Returns(new List<string>());
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.HeadingPath.Should().BeNull();
    }

    [Fact]
    public void HeadingPath_WithNullPath_ReturnsNull()
    {
        // Arrange
        _mockFluxIndexChunk.Setup(c => c.HeadingPath).Returns((IReadOnlyList<string>)null!);
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.HeadingPath.Should().BeNull();
    }

    [Fact]
    public void Summary_ReturnsNull_AsNotAvailableInFluxIndex()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        // FluxIndex chunks don't have Summary - this is generated by FluxImprover enrichment
        adapter.Summary.Should().BeNull();
    }

    [Fact]
    public void Keywords_ReturnsNull_AsNotAvailableInFluxIndex()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        // FluxIndex chunks don't have Keywords - this is generated by FluxImprover enrichment
        adapter.Keywords.Should().BeNull();
    }

    [Fact]
    public void Metadata_ContainsFluxIndexSpecificProperties()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act
        var metadata = adapter.Metadata;

        // Assert
        metadata.Should().NotBeNull();
        metadata!["ChunkIndex"].Should().Be(0);
        metadata["Quality"].Should().Be(0.85);
        metadata["ContextDependency"].Should().Be(0.3);
        metadata["TokenCount"].Should().Be(50);
        metadata["StartPage"].Should().Be(1);
        metadata["EndPage"].Should().Be(2);
        metadata["SectionTitle"].Should().Be("Section 1.1");
        metadata["FilePath"].Should().Be("/path/to/test.pdf");
        metadata["SourceType"].Should().Be("pdf");
    }

    [Fact]
    public void Metadata_OmitsNullValues()
    {
        // Arrange
        _mockFluxIndexChunk.Setup(c => c.TokenCount).Returns((int?)null);
        _mockFluxIndexChunk.Setup(c => c.StartPage).Returns((int?)null);
        _mockFluxIndexChunk.Setup(c => c.EndPage).Returns((int?)null);
        _mockFluxIndexChunk.Setup(c => c.SectionTitle).Returns((string?)null);
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act
        var metadata = adapter.Metadata;

        // Assert
        metadata.Should().NotContainKey("TokenCount");
        metadata.Should().NotContainKey("StartPage");
        metadata.Should().NotContainKey("EndPage");
        metadata.Should().NotContainKey("SectionTitle");
    }

    [Fact]
    public void Constructor_WithNullChunk_ThrowsArgumentNullException()
    {
        // Act & Assert
        var act = () => new EnrichedChunkAdapter(null!);
        act.Should().Throw<ArgumentNullException>()
            .WithParameterName("fluxIndexChunk");
    }

    [Fact]
    public void UnderlyingChunk_ReturnsOriginalFluxIndexChunk()
    {
        // Arrange
        var adapter = new EnrichedChunkAdapter(_mockFluxIndexChunk.Object);

        // Act & Assert
        adapter.UnderlyingChunk.Should().BeSameAs(_mockFluxIndexChunk.Object);
    }
}
